### ISSUE TITLE
Value being reverted to default value

### ISSUE THREAD

**Issue by markmiddleton** [riasvdv/craft-colour-swatches#29]
![issue-with-default-color-swatch](https://user-images.githubusercontent.com/2645384/71693355-1d9b0e00-2d61-11ea-8a42-2b6d1b8c91c7.png)

Upon editing a previously saved entry with the Colour swatches field, the color is reverted to the default color.

this can be repeated by:
1) open a previously saved entry using a colour swatches field (make sure the colour swatches field has a default value different from the currently selected value).
2) make no changes to the entry
3) save the entry
4) the colour is updated to the default colour.

**Comment by markmiddleton** [comment]
this fix worked for me:
https://github.com/brilliancenw/craft-colour-swatches/commit/783bfe586cdb9565fb80943fc9a92dbac52babee#diff-6a134583c1bcad2d1a17a733ca9aaac1

**Comment by riasvdv** [comment]
Can you send a PR for that? Then I'll just merge and release it!

**Comment by riasvdv** [comment]
Got it from your fork! Fixed in 1.2.7
